name: can_bagi
description: "Acil kan ihtiyacı durumunda bağışçıları ve hastaneleri buluşturan uygulama."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_messaging: ^14.7.20
  
  # HTTP requests
  http: ^1.1.0
  
  # Location services
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  
  # UI bileşenleri
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  # flutter_local_notifications: ^15.1.3  # Geçici olarak kaldırıldı
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # .env dosyasını assets'e ekleyelim
  assets:
    - .env
  
  # Assets klasörleri şimdilik kaldırıldı
  # İhtiyaç duyulduğunda tekrar eklenebilir
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/